// Start here
/* -------------------------------------------------- */
/* -------------------  PART 1 ---------------------- */
/* -------------------------------------------------- */
const displayHambergur = document.querySelector('.menu-toggle');
const ourNavbar = document.querySelector('.nav');

if (displayHambergur) {
  displayHambergur.addEventListener(
    'click',
    function navToggler() {
      ourNavbar.classList.toggle('nav');
      ourNavbar.classList.toggle('nav.is-active');
    },
    false,
  );
}

/* -------------------------------------------------- */
/* -------------------  PART 2 ---------------------- */
/* -------------------------------------------------- */
const submitBtn = document.querySelector('.btn-submit');
const checkBox = document.querySelector('.form-checkbox-control');
submitBtn.disabled = true;

function checkInput() {
  const requiredFormItems = document.querySelectorAll('.form-control');
  // Only return true if all the filled Items have value !== ''
  const allFilledItems = Array.from(requiredFormItems).every((filledItem) => filledItem.value !== '');
  if (checkBox.checked) {
    submitBtn.disabled = !allFilledItems;
  }
  // console.log('checkInput is running!');
}

document.querySelectorAll('.form-control').forEach((item) => {
  item.addEventListener('input', checkInput);
  // console.log('iteration input is working!');
});

checkBox.addEventListener('change', () => {
  if (checkBox.checked) {
    checkInput();
    // console.log('Checkbox is checked..');
  } else {
    // console.log('Checkbox is not checked..');
  }
});

/* -------------------------------------------------- */
/* -------------------  PART 3 ---------------------- */
/* -------------------------------------------------- */
const modal = document.getElementById('js-modal');
const toast = document.querySelector('.toast');
const form = document.querySelector('.form');
const closeBtn = document.querySelector('.btn-close');
const closeToastBtn = document.querySelector('.btn-close-sm');
const confirmBtn = document.querySelector('.btn-confirm');
const ourForms = document.forms[0]; // Accessing the form's items(child elements)

function isShow() {
  modal.classList.toggle('is-show');
}

// Displaying Data in the Modal Window:  (Targetting each input value : ourForms.name.value)
function getValues() {
  const formData = {
    name: ourForms.name.value,
    surname: ourForms.surname.value,
    email: ourForms.email.value,
    city: ourForms.dropdown.value,
    phone: ourForms.phone.value,
    date: ourForms.date.value,
    comment: ourForms.comment.value,
  };
  const listToShow = `
    <li>Fisrt Name: ${formData.name}</li>
    <li>Family Name: ${formData.surname}</li>
    <li>Email: ${formData.email}</li>
    <li>City: ${formData.city}</li>
    <li>Phone: ${formData.phone}</li>
    <li>Date: ${formData.date}</li>
    <li>Comment: ${formData.comment}</li>
  `;
  document.querySelector('.modal-list').innerHTML = listToShow;
}
// Modal Window Activation:
form.addEventListener('submit', function modalFunction(event) {
  event.preventDefault();
  isShow();
  getValues();
});

function isShowToast() {
  toast.classList.toggle('is-show');
  form.reset();
  setTimeout(() => {
    toast.classList.toggle('is-show');
  }, 3000);
}

// Modal Window Close Functionality:
closeBtn.addEventListener('click', isShow);
confirmBtn.addEventListener('click', function confButtton() {
  isShow();
  isShowToast();
});

/* -------------------------------------------------- */
/* ---------------- ADDITIONAL LEVEL ---------------- */
/* -------------------------------------------------- */

// The "Successfully sent" toast and Close Functionality:

closeToastBtn.addEventListener('click', isShowToast);

/* -------------------------------------------------- */
/* ----------------- OPTIONAL LEVEL ----------------- */
/* -------------------------------------------------- */

// Update the Date validation
document.addEventListener('DOMContentLoaded', () => {
  const today = new Date();
  const dd = String(today.getDate()).padStart(2, '0');
  const mm = String(today.getMonth() + 1).padStart(2, '0');
  const yyyy = today.getFullYear();

  const formatedDate = `${mm}-${dd}-${yyyy}`;
  const dateInput = document.getElementById('date');
  dateInput.setAttribute('min', formatedDate);
});

// Add/remove DOM elements
// For example by clicking a button "here the Submit Button", an element "div" will be added to the page dynamically
submitBtn.addEventListener('click', () => {
  const newDiv = document.createElement('div');
  newDiv.textContent = 'new element generated by user';
  newDiv.style.backgroundColor = 'lightblue';
  newDiv.style.margin = 'auto';
  newDiv.style.padding = '12px';
  document.getElementById('js-contacts').appendChild(newDiv);
});
